### ISSUE TITLE
Searchbar is in front of file toolbar

### ISSUE THREAD

**Issue by Chris2011** [marcosptf/stackoverflowNetbeansPlugin#1]
The stackoverflow toolbar is inside the file toolbar. I only can move the whole file toolbar. Please create your own toolbar for this. I don't use the file toolbar so I can hide it but than yours is hidden too.

Regards

Chris

**Comment by marcosptf** [comment]
hi @Chris2011, everything fine?
i have seen your comment on netbeans portal, i'll fix is asap.

thanks

**Comment by Chris2011** [comment]
Hey, I'm fine thx and you? Sry for the double post, I didn't see the github link so I switched to this here :)

**Comment by marcosptf** [comment]
hey @Chris2011 , don't worry, you are ever welcome!
:-)

you give one more follow in your github profile, myself!
kkkk

but....

i think ill need your help, becouse im beginner on develop pluguins to netbeans, and i've research on the internet and too netbeans documents and i dont found how i can fixed it.

can you help me?
thanks
:-)

**Comment by Chris2011** [comment]
I will have a look soon.

**Comment by Chris2011** [comment]
The fix is easy: Change "Toolbars/File" to "Toolbars/Stackoverflow" than you have your own, if the toolbar not exists. Thats it.

**Comment by Chris2011** [comment]
This is the fix: path = "Toolbars/Stackoverflow".

**Comment by marcosptf** [comment]
thanks @Chris2011 
ill fix it and update the plugin on plugin.netbeans.org portal
:-)
:+1:

**Comment by marcosptf** [comment]
hi @Chris2011 !!!
i've fixed the plugin like you said and i updated the netbeans plugins portal, can you help me  test again?

thanks!!!!

**Comment by marcosptf** [comment]
the status of the plugin is "waiting for approval", but you can download the new version with this endpoint:
http://plugins.netbeans.org/plugin/60090/?show=true

**Comment by Chris2011** [comment]
I tried it but now I have 2 stackoverflow panels. One inside the file, like before and one standalone. Please can you update the version too? It is still 1.0. For this I have to uninstall the old version. Set it to 1.1

**Comment by Chris2011** [comment]
Ok it seems to work, I checked it with an instance without installing the plugin before. So it works. But for the next time, please update the version.

**Comment by marcosptf** [comment]
@Chris2011 t
okey !
thanks for your contributions

**Comment by marcosptf** [comment]
:+1:

**Comment by javatlacati** [comment]
For a new install appeared twice... Downloaded file 1440460800_org-stackoverflow.nbm from netbeans plugin site.

You can guide on this plugin: https://github.com/CoderMasters/Jar-Searcher

![sin titulo](https://cloud.githubusercontent.com/assets/1063901/11480093/2493ee02-975b-11e5-9c6b-35946543fc1d.png)

**Comment by marcosptf** [comment]
hi @javatlacati, how are you?
fine?
i'll fix it asap, but this kind of but is funny, twice
kkkkkk
i never think that its possible

thanks for your report, have a nice day!
:-)

**Comment by Chris2011** [comment]
There is a little tutorial to implement such search fields like Stackoverflow or Jar-Searcher or Google into the Quick Search. I think this would be a better solution to not overload netbeans with such searchbars/toolbars. https://platform.netbeans.org/tutorials/nbm-quick-search.html

**Comment by marcosptf** [comment]
@Chris2011 @javatlacati 
:+1:
